# Generated by Django 5.1.2 on 2025-05-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='bmi',
        ),
    ]
