# Generated by Django 5.1.2 on 2025-05-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_remove_healthrecord_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='bmi',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
