# Generated by Django 5.1.2 on 2025-05-15 16:35

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_healthrecord_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='birthday',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('bio', ckeditor.fields.RichTextField(blank=True, help_text='Giới thiệu bản thân', null=True)),
                ('specialties', models.CharField(help_text='Ví dụ: Gym, Yoga, Cardio...', max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
