# Generated by Django 5.1.2 on 2025-05-16 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_remove_healthrecord_birthday_healthrecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
