# Generated by Django 5.1.2 on 2025-05-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0005_alter_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
