# Generated by Django 5.1.2 on 2025-06-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0006_remove_user_birthday_activity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Exerciser_self_help'), (2, 'Exerciser_with_coach'), (3, 'Coach')], default=0),
        ),
    ]
