# Generated by Django 5.1.2 on 2025-06-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthdiary',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='goal_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
