# Generated by Django 5.1.2 on 2025-06-05 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthdiary',
            options={'ordering': ['-id']},
        ),
    ]
