# Generated by Django 5.1.2 on 2025-06-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0009_remove_healthrecord_sleep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
